name: Release
"on":
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
permissions:
  contents: read
jobs:
  UpdateReleaseDraft:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    needs:
      - PublishBetaRelease
    steps:
      - name: Draft next release
        uses: release-drafter/release-drafter@v6
        with:
          commitish: main
          prerelease: false # the default
          include-pre-releases: false # the default
          publish: false # the default
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PublishBetaRelease:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.event_name == 'push'
    permissions:
      contents: write
    steps:
      - name: Publish beta release
        uses: release-drafter/release-drafter@v6
        with:
          commitish: main
          config-name: release-drafter.prerelease.yml
          prerelease: true
          prerelease-identifier: beta
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
