name: Publish Release
"on":
  release:
    types:
      - published
      - prereleased
jobs:
  PublishPackages:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - name: Test
        run: echo test
